// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ClustMeans
NumericMatrix ClustMeans(int nclust, IntegerVector start, NumericMatrix data);
RcppExport SEXP lsbclust_ClustMeans(SEXP nclustSEXP, SEXP startSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type nclust(nclustSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type start(startSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP );
        NumericMatrix __result = ClustMeans(nclust, start, data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// LossMat
NumericMatrix LossMat(NumericMatrix x, NumericMatrix y);
RcppExport SEXP lsbclust_LossMat(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP );
        NumericMatrix __result = LossMat(x, y);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
