// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ClustMeans
NumericMatrix ClustMeans(int nclust, IntegerVector start, NumericMatrix data);
RcppExport SEXP lsbclust_ClustMeans(SEXP nclustSEXP, SEXP startSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type nclust(nclustSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    __result = Rcpp::wrap(ClustMeans(nclust, start, data));
    return __result;
END_RCPP
}
// LossMat
NumericMatrix LossMat(NumericMatrix x, NumericMatrix y);
RcppExport SEXP lsbclust_LossMat(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    __result = Rcpp::wrap(LossMat(x, y));
    return __result;
END_RCPP
}
